'use strict';

export const pizza = [
  {
    id: 1,
    new: true,
    name: 'Піца з грушею та сиром Дорблю',
    description: 'Вершковий соус Альфредо, фета, дорблю, Моцарела',
    imgMobile: '../img/desktop/grusha.png',
    imgMobile2x: '../img/desktop/grusha.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha.png',
    price: '165',
  },

  {
    id: 2,
    new: false,
    name: 'Піца Капрічоза',
    description: 'Шинка, маслини, помідори, сир Моцарела, соус бешамель ',
    imgMobile: '../img/desktop/capricosa-menu.png',
    imgMobile2x: '../img/desktop/capricosa-menu.png',
    imgDesktop: '../img/desktop/capricosa-menu.png',
    imgDesktop2x: '../img/desktop/capricosa-menu.png',
    price: '165',
  },
  {
    id: 3,
    new: false,
    name: 'Піца Козацька гостра',
    description:
      'Томатний гострий соус,  мисливські ковбаски,  салямі, куряче філе, солений огірок, помідори, синя цибуля перець Чилі',
    imgMobile: '.../img/desktop/cossack.png',
    imgMobile2x: '../img/desktop/cossack.png',
    imgDesktop: '../img/desktop/cossack.png',
    imgDesktop2x: '../img/desktop/cossack.png',
    price: '165',
  },
  {
    id: 4,
    new: false,
    name: 'Піца 4 Сири',
    description: 'Вершковий соус Альфредо, фета, дорблю, Моцарела',
    imgMobile: '../img/desktop/chesee.png',
    imgMobile2x: '../img/desktop/chesee.png',
    imgDesktop: '../img/desktop/chesee.png',
    imgDesktop2x: '../img/desktop/chesee.png',
    price: '167',
  },

  {
    id: 5,
    new: false,
    name: 'Піца Гавайська',
    description:
      'Сир Моцарела, ананаси консервовані, куряче філе,  кукурудза консервована,  соус вершковий «Альфредо» ',
    imgMobile: '../img/desktop/havai.png',
    imgMobile2x: '../img/desktop/havai.png',
    imgDesktop: '../img/desktop/havai.png',
    imgDesktop2x: '../img/desktop/havai.png',
    price: '165',
  },

  {
    id: 6,
    new: false,
    name: 'Піца Бургер',
    description:
      'Яловичина, бекон, солений огірок, синя цибуля, томатний соус, цибулевий мармелад,  соус Чеддер Сир Моцарела',
    imgMobile: '../img/desktop/burgerpizza.png',
    imgMobile2x: '../img/desktop/burgerpizza.png',
    imgDesktop: '../img/desktop/burgerpizza.png',
    imgDesktop2x: '../img/desktop/burgerpizza.png',
    price: '165',
  },
];

export const burgers = [
  {
    id: 101,
    new: true,
    name: 'Бургер з яловичиною',
    imgMobile: '../img/desktop/burger.png',
    imgMobile2x: '../img/desktop/burger.png',
    imgDesktop: '../img/desktop/burger.png',
    imgDesktop2x: '../img/desktop/burger.png',
    price: '200',
  },
  {
    id: 102,
    new: false,
    name: 'Бургер Чорний подвійний',
    imgMobile: '../img/desktop/black.png',
    imgMobile2x: '../img/desktop/black.png',
    imgDesktop: '../img/desktop/black.png',
    imgDesktop2x: '../img/desktop/black.png',
    price: '200',
  },
  {
    id: 103,
    new: false,
    name: 'Бургер Фреш з куркою',
    imgMobile: '../img/desktop/fresh.png',
    imgMobile2x: '../img/desktop/fresh.png',
    imgDesktop: '../img/desktop/fresh.png',
    imgDesktop2x: '../img/desktop/fresh.png',
    price: '200',
  },
  {
    id: 104,
    new: false,
    name: 'Бургер з Куркою',
    imgMobile: '../img/desktop/chicken.png',
    imgMobile2x: '../img/desktop/chicken.png',
    imgDesktop: '../img/desktop/chicken.png',
    imgDesktop2x: '../img/desktop/chicken.png',
    price: '200',
  },
];

export const pita = [
  {
    id: 201,
    new: true,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
  {
    id: 202,
    new: false,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
  {
    id: 203,
    new: false,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
  {
    id: 204,
    new: false,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
];
