'use strict';

export const pizza = [
  {
    id: 1,
    new: true,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },

  {
    id: 2,
    new: false,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },
  {
    id: 3,
    new: false,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },
  {
    id: 4,
    new: false,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },

  {
    id: 5,
    new: false,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },

  {
    id: 6,
    new: false,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },

  {
    id: 7,
    new: false,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },

  {
    id: 8,
    new: false,
    name: 'Піца з грушею та сиром Дорблю',
    imgMobile: '../img/mobile/pizza.png',
    imgMobile2x: '../img/mobile/pizza@2x.png',
    imgDesktop: '../img/desktop/grusha.png',
    imgDesktop2x: '../img/desktop/grusha@2x.png',
    price: '165',
  },
];

export const burgers = [
  {
    id: 101,
    new: true,
    name: 'Бургер з яловичиною',
    imgMobile: '../img/mobile/burger.png',
    imgMobile2x: '../img/mobile/burger@2x.png',
    imgDesktop: '../img/desktop/burger.png',
    imgDesktop2x: '../img/desktop/burger@2x.png',
    price: '200',
  },
  {
    id: 102,
    new: false,
    name: 'Бургер з яловичиною',
    imgMobile: '../img/mobile/burger.png',
    imgMobile2x: '../img/mobile/burger@2x.png',
    imgDesktop: '../img/desktop/burger.png',
    imgDesktop2x: '../img/desktop/burger@2x.png',
    price: '200',
  },
  {
    id: 103,
    new: false,
    name: 'Бургер з яловичиною',
    imgMobile: '../img/mobile/burger.png',
    imgMobile2x: '../img/mobile/burger@2x.png',
    imgDesktop: '../img/desktop/burger.png',
    imgDesktop2x: '../img/desktop/burger@2x.png',
    price: '200',
  },
  {
    id: 104,
    new: false,
    name: 'Бургер з яловичиною',
    imgMobile: '../img/mobile/burger.png',
    imgMobile2x: '../img/mobile/burger@2x.png',
    imgDesktop: '../img/desktop/burger.png',
    imgDesktop2x: '../img/desktop/burger@2x.png',
    price: '200',
  },
];

export const pita = [
  {
    id: 201,
    new: true,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
  {
    id: 202,
    new: false,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
  {
    id: 203,
    new: false,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
  {
    id: 204,
    new: false,
    name: 'Піта з яловичиною',
    imgMobile: '../img/mobile/pita.png',
    imgMobile2x: '../img/mobile/pita@2x.png',
    imgDesktop: '../img/desktop/pita.png',
    imgDesktop2x: '../img/desktop/pita@2x.png',
    price: '85',
  },
];
